name: Hello macOS

on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Say Hello
      run: echo "hello"
